title               : Albin
description         : Portfolio of Md. Albin Hossain.
baseurl             : ""
url                 : https://albin.com.bd
repository          : MdAlbinHossain/MdAlbinHossain.github.io
api                 : /api/forms/

author:
  name              : Md. Albin Hossain
  description       : Hi there! I am Albin. Nice to meet you!
  address           : Virtually Everywhere
  city              : Narayanganj
  country           : Bangladesh
  phone             : "+8809697495705"
  email             : mail@albin.com.bd
  social_links:
   - { platform: email,          user_url: "mailto:mail@albin.com.bd"}
   - { platform: telegram,       user_url: "https://t.me/MdAlbinHossain" }
   - { platform: github,         user_url: "https://github.com/MdAlbinHossain" }
   - { platform: linkedin,       user_url: "https://linkedin.com/in/Md-Albin-Hossain" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/Md.Albin.Hosssain" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/Md.Albin.Hossain" }
  #  - { platform: threads,      user_url: "https://www.threads.net/Md.Albin.Hossain" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/23159657/albin" }
   - { platform: youtube,        user_url: "https://www.youtube.com/@MdAlbinHossain" }
  #  - { platform: twitter,        user_url: "https://twitter.com/MdAlbinHossain" }
  #  - { platform: reddit,         user_url: "https://www.reddit.com/user/MdAlbinHossain" }
  #  - { platform: medium,         user_url: "https://medium.com/@MdAlbinHossain" }
  #  - { platform: dev,            user_url: "https://dev.to/MdAlbinHossain" }
  #  - { platform: codepen,        user_url: "https://codepen.io/MdAlbinHossain" }
  #  - { platform: gitlab,         user_url: "https://gitlab.com/MdAlbinHossain" }
  #  - { platform: discord,        user_url: "https://discord.com/users/1234567890" }

# Build settings
# theme: minima

colors: [primary, secondary, success, danger, warning, info, dark]

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 10

permalink: /blog/:title
paginate_path: /blog/page:num/

collections:
 projects:
  output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      permalink: /projects/:name

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docs
  - api
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

compress_html:
  clippings: all

# google-site-verification: 2hINLENEyfOQQnSezXVDFIn0nSrV_8d0V_RopdbxVKM