title: Albin's Page
description: Albin's personal webpage.

author:
  name: Md. Albin Hossain
  email: albin@albin.com.bd

baseurl: ""
url: "https://MdAlbinHossain.github.io"

collections:
  projects:
    output: true
    permalink: /projects/:path/

social_links:
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/MdAlbinHossain" }
  - { platform: instagram,      user_url: "https://www.instagram.com/Md.Albin.Hossain" }
  - { platform: facebook,       user_url: "https://www.facebook.com/Md.Albin.Hossain" }
  - { platform: youtube,        user_url: "https://www.youtube.com/@MdAlbinHossain" }
  - { platform: twitter,        user_url: "https://twitter.com/MdAlbinHossain" }
  - { platform: github,         user_url: "https://github.com/MdAlbinHossain" }
  - { platform: telegram,       user_url: "https://t.me/MdAlbinHossain" }

show_excerpts: true

exclude: 
  - Gemfile