source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-default-layout"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-include-cache"
gem 'jekyll-sitemap'
gem "jemoji"
gem "kramdown"
gem "webrick", "~> 1.8"
gem "jekyll-seo-tag", "~> 2.8"
